### PR TITLE
exeresicse

### PR DESCRIPTION
**Pull request by ahmedomarshahhat**
http://localhost:8888/notebooks/NumberReprestitation_exercises.ipynb 
http://localhost:8888/notebooks/Fundamentals_exercises%20.ipynb
http://localhost:8888/notebooks/Introduction_exercises%20.ipynb
http://localhost:8888/notebooks/numpayexersices%20.ipynb

### CODE REVIEW

**Comment by Mmiglio** [comment]
Pull Requests MUST NOT be addressed towards the master of the central repository, please redo it pointing to the proper branch!

**Comment by ahmedomarshahhat** [comment]
Good morning,

I just pulled them now again, can you confirm me if everything is OK now
and thanks in advance.

Best Regards

Il mar 3 nov 2020, 09:15 Matteo Migliorini <notifications@github.com> ha
scritto:

**Comment by ahmedomarshahhat** [comment]
#174 pull number

Il mar 3 nov 2020, 11:36 Ahmed Omar Younus Shahhat <
ahmedomaryounus.shahhat@studenti.unipd.it> ha scritto:

**Comment by Mmiglio** [comment]
yes, now it is fine.

**Pull request closed without merging**
