### PR TITLE
0. Babak Pornour Mehravani------Exercise set of the month "October"

### PR DESCRIPTION
**Pull request by BabakMehravani**

### CODE REVIEW

**Comment by Mmiglio** [comment]
Pull Requests MUST NOT be addressed towards the master of the central repository, please redo it pointing to the proper branch!

**Comment by BabakMehravani** [comment]
I first committed it then compare and pull. Finally I pulled it!
What I have to do exactly?

**Comment by Mmiglio** [comment]
You need to address the pull request pointing to the branch with your
name_surname of the central repository. Instead you addressed it towards
the master.

**Comment by BabakMehravani** [comment]
Dear Matteo,

Could you please check it out and see if I have done it correctly or not?!

   Bests,
Babak

**Comment by Mmiglio** [comment]
yes, now it is correct.

**Pull request closed without merging**
