### PR TITLE
Shahhat ahmed

### PR DESCRIPTION
**Pull request by ahmedomarshahhat**

### CODE REVIEW

**Comment by zucchett** [comment]
Don't do the PR to the master! I'm closing this PR, please make a new one pointing to your own branch.

**Comment by ahmedomarshahhat** [comment]
Dear Dott.Zucchetta,
Hope my email finds you well,

I was trying to do it in the way that you wrote me but unfortunately it
gives me always that there is nothing to compare with my brunch as you can
see in the attachments with this mail.

Best regards
Ahmed shahhat.


Il mer 30 dic 2020, 12:22 Alberto Zucchetta <notifications@github.com> ha
scritto:

**Comment by zucchett** [comment]
Messages through github, like this one, usually do not accept attachments.
However, we merged another PR from you yesterday:
https://github.com/PhysicsOfData/LaboratoryOfComputationalPhysics_Y3/tree/Shahhat_Ahmed
If that's everything, we already marked your exercises.

**Comment by ahmedomarshahhat** [comment]
Dear Dott.Zucchetta,

I saw the link and I have all my exercises there. Thank you for your help
and understanding .

best regards.
Ahmed Shahhat.

Il giorno gio 31 dic 2020 alle ore 11:39 Alberto Zucchetta <
notifications@github.com> ha scritto:

**Pull request closed without merging**
