### PR TITLE
Pull request for 07.2ex 08ex and 09ex

### PR DESCRIPTION
**Pull request by LorenzoBuriola**
Third pull request for LoCP assignment. The jupyter notebook files were already merged with the previous pull request.

### CODE REVIEW

**Comment by LorenzoBuriola** [comment]
All three files were merged already with the previous pull request. I opened this just to have a third pull request.

**Comment by Mmiglio** [comment]
Hi, can I merge this Pull Request? everything is looking good to me.

**Comment by LorenzoBuriola** [comment]
Hi,
yes, I opened it in order to have formally a third pull request for the
third set of assignment, but the last exercises were also in the previous
(second) pull request.
Thanks

Il giorno lun 28 dic 2020 alle ore 18:29 Matteo Migliorini <
notifications@github.com> ha scritto:

**Comment by Mmiglio** [comment]
I see. I've already taken into account the exercises of the third set.

**Pull request merged**
