### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by GholamiMaryam**

### CODE REVIEW

**Comment by Mmiglio** [comment]
Pull Requests MUST NOT be addressed towards the master of the central repository, please redo it pointing to the proper branch!

You need also to solve conflicts, otherwise it is not possible to merge the branch.

**Comment by GholamiMaryam** [comment]
Dear
I have a little bit problem with git hub, please clarify and explain more
what I should do to solve the problem.
Thank you

Il giorno mar 3 nov 2020 alle ore 11:43 Matteo Migliorini <
notifications@github.com> ha scritto:

**Comment by Mmiglio** [comment]
Hi,

I closed your pull request because you were addressing it towards the
master branch of the upstream repository. You should open in it again
pointing to the right branch (the one with your name)

**Comment by GholamiMaryam** [comment]
Hi,
I opened it again and changed master name with my name. Would you please
check if it is correct now?
Thank you


Il giorno mar 3 nov 2020 alle ore 15:45 Matteo Migliorini <
notifications@github.com> ha scritto:

**Comment by Mmiglio** [comment]
Send me the link of that PR

**Pull request closed without merging**
