### PR TITLE
00ex added

### PR DESCRIPTION
**Pull request by Tungcg1906**

### CODE REVIEW

**Comment by zucchett** [comment]
Please do not include jupyter checkpoints, logs or other files except the lesson/exercises notebooks in the next PRs.
02ex and 03ex are empty.

**Comment by Tungcg1906** [comment]
Dear Aberto,

This is the very first set of exercise, I think it only contain 00ex. 
Should I redo this?

**Comment by zucchett** [comment]
It contains both 00ex and 01ex, and they are fine, but 02ex and 03ex are missing. Are they somewhere else, e.g. in another PR?

**Comment by Tungcg1906** [comment]
Yes, all 00ex, 01eex, 02ex, 03ex are contained in another branch, I made a pull request for all of them named FirstSetOfHW_Tung

**Comment by zucchett** [comment]
Ok, i see them. We didn't reach the other PR yet, i'll merge it now.

**Pull request merged**
