### PR TITLE
Exercise 00ex + 01ex + 02ex + 03ex

### PR DESCRIPTION
**Pull request by francescofontana97**
Add 00ex & 01ex file completed

### CODE REVIEW

**Comment by zucchett** [comment]
Before merging, could you please:
1) fix the error in 06ex
2) some exercises have cells that have not been executed.
After you will push the updated files, i'll merge the pull request.

**Comment by zucchett** [comment]
Ok, thanks. I marked the exercises up to 06ex, so, you don't have to include them in the next PR.

**Comment by francescofontana97** [comment]
Ok, thanks, but what do you mean when saying that I don't have to  include them in the next  pull request? Could I choose each file to be merged individually instead of the entire branch?

**Comment by francescofontana97** [comment]
And also can I delete all the file from the this branch that not concern with the exercises? (I mean, keeping only the exercises completed? Thanks

**Comment by zucchett** [comment]
No, you can merge only an entire branch, but it you decide to delete the current branch and open a new one you can put only the new exercises there. If you decide to continue using the current development branch, you don't have to do anything.
Yes, you can delete all other files that do not concern the exercises.

**Pull request merged**
