### PR TITLE
UPDATED EXERCISES Zambelli Francesco

### PR DESCRIPTION
**Pull request by francescozambelli**
Hello professor,
in today's class I had some problems obtaining the updates for the lesson so I tried to fix some stuff about git. In the meanwhile I realized that maybe I did the pull request of the exercises with a not updated version of my homework. Can I ask you if you can check whether or not I sent the version of exercises 03 with my code or only the instructions of the professor? In the case now I should have updated correctly all the github stuff, can I do something to update my pull request?
Thanks

### CODE REVIEW

**Comment by zucchett** [comment]
Indeed, some of the notebooks are unreadable. Please remove the conflicts either through git or by hand removing the lines that look like this:
<<<<<<< HEAD
<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> master
Please fix 00ex, 01ex, 03ex so we can mark them and merge the PR.
Also please remember to run all cells before committing the files.

**Comment by francescozambelli** [comment]
Hello,
I think I managed to fix the problems.
Thank you for the notification
Francesco

Il giorno lun 30 nov 2020 alle ore 11:44 Alberto Zucchetta <
notifications@github.com> ha scritto:

**Comment by francescozambelli** [comment]
Volevo anche chiederle se mi fosse possibile posticipare la consegna del
secondo set di esercizi causa discussione di laurea questa settimana
La ringrazio e le auguro una buona serata

Francesco Zambelli

Il giorno lun 30 nov 2020 alle ore 16:29 francesco zambelli <
francesco.zambelli98@gmail.com> ha scritto:

**Comment by zucchett** [comment]
Va bene, non c'e' problema.

**Pull request merged**
