### PR TITLE
Exercises 0-3

### PR DESCRIPTION
**Pull request by leonellielena**

### CODE REVIEW

**Comment by zucchett** [comment]
Hi,  i just want to understand if all exercises are ready to be marked because some look incomplete. If so, i'll mark as they are; if not, i'll wait for the next commit. Also consider that when we merge the pull request, we can't hand-pick which file is merged or not; we merge the whole branch.
Also, could you please run all the cells of all the exercises, so we can check the output?

**Comment by leonellielena** [comment]
Hi,
I run all the cells of exercises 0-3. Some weeks ago I had a problem with
Matteo Migliorini because he opened my notebooks with another version of
python, and I uploaded an older version of them to resolve the problem.
Anyway, the notebooks are now correct.
Please consider only exercises 0-3 and not 4-7.1: I wrote some day ago a
mail to explain that I'll made the pull request of the second set of
exercises in late, because I have my bachelor degree next week.

Tell me if there are other problems.

Elena Leonelli

Il giorno sabato 28 novembre 2020, Alberto Zucchetta <
notifications@github.com> ha scritto:

**Comment by zucchett** [comment]
Thanks, ex 00-03 are fine. But pull requests merge entire branches, not single files. So i have to either merge all of them, or just wait for the other exercises to be ready (with no penalty for you, of course) and then merge them all. I would opt for the second option, but if you prefer otherwise, please let me know.

**Comment by leonellielena** [comment]
As you want, i'll do another pull request when the second set of exercises
are ready. You can wait.if you prefer.

Il giorno sabato 28 novembre 2020, Alberto Zucchetta <
notifications@github.com> ha scritto:

**Comment by zucchett** [comment]
Ok, let's wait for the second set of exercises.

**Comment by leonellielena** [comment]
Buongiorno,
volevo comunicare che ho terminato il secondo set di esercizi e li ho ora
caricati nella mia repository.
Buona giornata,
Elena Leonelli

Il giorno lun 30 nov 2020 alle ore 11:11 Alberto Zucchetta <
notifications@github.com> ha scritto:

**Comment by zucchett** [comment]
Thanks, i'm merging the branch. Since you included the 07.2ex file, please make sure to synchronize your branch before modifying that file.

**Comment by leonellielena** [comment]
Yes of course, thank you!

Il Gio 10 Dic 2020, 16:52 Alberto Zucchetta <notifications@github.com> ha
scritto:

**Pull request merged**
